
name: 'dbt_project_1'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_dev'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_project_1:
    example:
      +materialized: view
